/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exam.project.by.jatin.mitesh.divyang;

/**
 *
 * @author Dell
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class CREATES extends javax.swing.JFrame {

    /**
     * Creates new form CREATES
     */
    public CREATES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Create Table home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(290, 200, 240, 50);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("Create Database jk ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(150, 10, 240, 50);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("Create Table login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(20, 90, 240, 50);
        jDesktopPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("Create Table travel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(300, 310, 240, 50);
        jDesktopPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("Create Table life");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(20, 310, 240, 50);
        jDesktopPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("Create Table bike");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(290, 90, 240, 50);
        jDesktopPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton7.setText("Create Table car");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(20, 200, 240, 50);
        jDesktopPane1.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
  String Q="create table home(ci_no varchar(30) primary key not null,netmoninc decimal(10,2) not null,price decimal(15,2) not null,DOC_TYPE varchar(20) not null,Loan_Amt decimal(15,2) not null,INS_COMP varchar(20) not null,Totalcover_Rs decimal(10,2),premium decimal(10,2) not null);";
  Class.forName("java.sql.Driver");
  Connection c=DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
  Statement st=c.createStatement();
  st.executeUpdate(Q);
  JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Table Created",null,2);
    
    
}
catch(Exception e){}            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
  String Q="create database jk;";
  Class.forName("java.sql.Driver");
  Connection c=DriverManager.getConnection("jdbc:mysql://localhost/information_schema","root","mysql");
  Statement st=c.createStatement();
  st.executeUpdate(Q);
  JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Database Created",null,2);
    
    
}
catch(Exception e){}
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
  String Q="create table login(LoginId varchar(30) primary key not null,Password varchar(30) not null);";
  Class.forName("java.sql.Driver");
  Connection c=DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
  Statement st=c.createStatement();
  st.executeUpdate(Q);
  JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Table Created",null,2);
    
    
}
catch(Exception e){}     

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
  String Q="create table travel(name varchar(30) primary key not null,amount decimal(15,2) not null,travelling_To varchar(30) not null,travellers varchar(30) not null,selfname varchar(30) not null,selfage int(3) not null,spousename varchar(30) ,spouseage int(3),child1name varchar(30),child1age int(3),child2name varchar(30),child2age int(3),child3name varchar(30),child3age int(3),INS_COMP varchar(20) not null,Totalcover_Rs decimal(10,2),premium decimal(15,2) not null);";
  Class.forName("java.sql.Driver");
  Connection c=DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
  Statement st=c.createStatement();
  st.executeUpdate(Q);
  JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Table Created",null,2);
    
    
}
catch(Exception e){}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try{
  String Q="create table life(name varchar(30) primary key not null,amount decimal(15,2) not null,no_of_mem int(2) not null,mem1 varchar(30) not null,age1 int(3) not null,mem2 varchar(30) ,age2 int(3),mem3 varchar(30),age3 int(3),mem4 varchar(30),age4 int(3),mem5 varchar(30),age5 int(3),INS_COMP varchar(20) not null,Totalcover_Rs decimal(10,2),premium decimal(10,2) not null);";
  Class.forName("java.sql.Driver");
  Connection c=DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
  Statement st=c.createStatement();
  st.executeUpdate(Q);
  JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Table Created",null,2);
    
    
}
catch(Exception e){}             // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try{
  String Q="create table bike(bike_no varchar(30) primary key not null,yr_use int(5) not null,price decimal(10,2) not null,bike_com varchar(20) not null,INS_COMP varchar(20) not null,Totalcover_Rs decimal(10,2),premium decimal(10,2) not null);";
  Class.forName("java.sql.Driver");
  Connection c=DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
  Statement st=c.createStatement();
  st.executeUpdate(Q);
  JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Table Created",null,2);
    
    
}
catch(Exception e){}          





// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try{
  String Q="create table car(car_no varchar(30) primary key not null,yr_use int(5) not null,price decimal(10,2) not null,car_com varchar(20) not null,INS_COMP varchar(20) not null,Totalcover_Rs decimal(10,2),premium decimal(10,2) not null);";
  Class.forName("java.sql.Driver");
  Connection c=DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
  Statement st=c.createStatement();
  st.executeUpdate(Q);
  JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Table Created",null,2);
    
    
}
catch(Exception e){}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CREATES().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
