
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1232
 */
public class LIFEins extends javax.swing.JFrame {

    /**
     * Creates new form CAR_INS
     */
    public LIFEins() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nm2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ea = new javax.swing.JTextField();
        ci = new javax.swing.JTextField();
        d2 = new javax.swing.JCheckBox();
        d3 = new javax.swing.JCheckBox();
        d1 = new javax.swing.JCheckBox();
        a1 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JCheckBox();
        but1 = new javax.swing.JButton();
        b2 = new javax.swing.JCheckBox();
        b3 = new javax.swing.JCheckBox();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        but2 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nm3 = new javax.swing.JLabel();
        nm4 = new javax.swing.JLabel();
        nm5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mem1 = new javax.swing.JTextField();
        mem2 = new javax.swing.JTextField();
        mem3 = new javax.swing.JTextField();
        mem4 = new javax.swing.JTextField();
        mem5 = new javax.swing.JTextField();
        age1 = new javax.swing.JTextField();
        age2 = new javax.swing.JTextField();
        age3 = new javax.swing.JTextField();
        age4 = new javax.swing.JTextField();
        age5 = new javax.swing.JTextField();
        nm1 = new javax.swing.JLabel();
        a4 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        b4 = new javax.swing.JCheckBox();
        d4 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/DHFL.png"))); // NOI18N
        jLabel1.setText("  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/hdfc.png"))); // NOI18N
        jLabel3.setText("   ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 58, -1, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("<");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 2, 2));
        jLabel4.setText("Compare Top Insurance Companies");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/exide life.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/bajaj.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        nm2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm2.setText("2nd Member");
        getContentPane().add(nm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Select Member's :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Enter Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 110, -1));
        getContentPane().add(ea, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, 120, -1));
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 160, -1));

        d2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d2.setText("Term Renew Plan get 40% less Premium (free)");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 320, -1));

        d3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d3.setText("Additional Accident cover of 1 lac (Rs.290/prs.)");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        d1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d1.setText("Govt.'s Driver Accident cover of 15 lac (Rs.2500)");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        a1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a1.setText("Govt.'s Driver Accident cover of 15 lac (Rs.1820)");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        a2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a2.setText("Term Renew Plan get 40% less Premium (free)");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 320, -1));

        a3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a3.setText("Additional Accident cover of 1 lac (Rs.410/prs.)");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setText("Govt.'s Driver Accident cover of 15 lac (Rs.2170)");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        but1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but1.setText("Count my Premium/yr.");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        getContentPane().add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setText("Term Renew Plan get 40% less Premium (free)");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 320, -1));

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setText("Additional Accident cover of 2 lac (Rs.740/prs.)");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        c1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c1.setText("Govt.'s Driver Accident cover of 15 lac (Rs.1740)");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 330, -1));

        c2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c2.setText("Term Renew Plan get 40% less Premium (free)");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 330, -1));

        c3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c3.setText("Additional Accident cover of 1.5 lac (Rs.620/prs.)");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        but2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but2.setText("Count my Premium/yr.");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });
        getContentPane().add(but2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        but4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but4.setText("Count my Premium/yr.");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });
        getContentPane().add(but4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        but3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but3.setText("Count my Premium/yr.");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });
        getContentPane().add(but3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Enter Amount :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 110, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        nm3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm3.setText("3rd Member ");
        getContentPane().add(nm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 80, -1));

        nm4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm4.setText("4rth Member ");
        getContentPane().add(nm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        nm5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm5.setText("5th Member ");
        getContentPane().add(nm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 80, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setText("Age");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 390, 40, -1));

        mem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem1ActionPerformed(evt);
            }
        });
        getContentPane().add(mem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 110, -1));

        mem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem2ActionPerformed(evt);
            }
        });
        getContentPane().add(mem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 110, -1));

        mem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem3ActionPerformed(evt);
            }
        });
        getContentPane().add(mem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 110, -1));

        mem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem4ActionPerformed(evt);
            }
        });
        getContentPane().add(mem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 110, -1));

        mem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem5ActionPerformed(evt);
            }
        });
        getContentPane().add(mem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 110, -1));

        age1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age1ActionPerformed(evt);
            }
        });
        getContentPane().add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 40, -1));

        age2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age2ActionPerformed(evt);
            }
        });
        getContentPane().add(age2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 40, -1));

        age3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age3ActionPerformed(evt);
            }
        });
        getContentPane().add(age3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 40, -1));

        age4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age4ActionPerformed(evt);
            }
        });
        getContentPane().add(age4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 40, -1));

        age5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age5ActionPerformed(evt);
            }
        });
        getContentPane().add(age5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 530, 40, -1));

        nm1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm1.setText("1st Member");
        getContentPane().add(nm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 80, -1));

        a4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a4.setText("Lifetime Medical Service (Rs.480/prs.)");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, -1));

        c4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c4.setText("Lifetime Medical Service (Rs.640/prs.)");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 330, -1));

        b4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b4.setText("Lifetime Medical Service (Rs.820/prs.)");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 320, -1));

        d4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d4.setText("Lifetime Medical Service (Rs.570/prs.)");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });
        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 320, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ADD TO CART");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("ADD TO CART");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("OPEN CART");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("MODIFY DETAILS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("ADD TO CART");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/backkkground.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new main_site().setVisible(true);
dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
String a,b,c;

a=ci.getText();
b=ea.getText();
c=mem1.getText();

if(a.isEmpty() || b.isEmpty() || c.isEmpty()){
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);}
Float cov=0f;
if(a1.isSelected())
cov+=1820;
if(a2.isSelected())
cov+=0;
if(a3.isSelected())
cov+=410;
if(a4.isSelected())
    cov+=480;

        
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);


    

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4000);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4000);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(4000);
        break;
}


pre=p1+p2+p3+p4+p5+cov;
but1.setText(""+pre);
                       // TODO add your handling code here:
    }//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
String a,b,c;
a=ci.getText();
b=ea.getText();
c=mem1.getText();
if(a.isEmpty() || b.isEmpty() || c.isEmpty())
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);
Float cov=0f;
if(b4.isSelected())
    cov+=820;
if(b1.isSelected())
cov+=2170f;
if(b2.isSelected())
cov+=0f;
if(b3.isSelected())
cov+=740f;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);
String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4500);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4500);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(4500);
        break;
}

pre=p1+p2+p3+p4+p5+cov;
but2.setText(""+pre);       // TODO add your handling code here:
    }//GEN-LAST:event_but2ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
String a,b,c;

a=ci.getText();
b=ea.getText();
c=mem1.getText();

if(a.isEmpty() || b.isEmpty() || c.isEmpty()){
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);}
Float cov=0f;
if(c1.isSelected())
cov+=1740;
if(c2.isSelected())
cov+=0;
if(c3.isSelected())
cov+=620;
if(c4.isSelected())
    cov+=640;
        
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);


    

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(5000);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(5000);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(5000);
        break;
}


pre=p1+p2+p3+p4+p5+cov;
but4.setText(""+pre);
         // TODO add your handling code here:
    }//GEN-LAST:event_but4ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
String a,b,c;

a=ci.getText();
b=ea.getText();
c=mem1.getText();

if(a.isEmpty() || b.isEmpty() || c.isEmpty()){
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);}
int cov=0;
if(d1.isSelected())
cov+=2500;
if(d2.isSelected())
cov+=0;
if(d3.isSelected())
cov+=290;
if(d4.isSelected())
    cov+=570;

        
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);


    

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(3590);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(3590);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(3590);
        break;
}


pre=p1+p2+p3+p4+p5+cov;
but3.setText(""+pre);
        // TODO add your handling code here:
    }//GEN-LAST:event_but3ActionPerformed

    private void mem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mem1ActionPerformed

    private void mem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mem2ActionPerformed

    private void mem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mem3ActionPerformed

    private void mem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mem4ActionPerformed

    private void mem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mem5ActionPerformed

    private void age1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_age1ActionPerformed

    private void age2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age2ActionPerformed

    private void age3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age3ActionPerformed

    private void age4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age4ActionPerformed

    private void age5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
mem2.setVisible(false);
mem3.setVisible(false);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(false);
age3.setVisible(false);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(false);
nm3.setVisible(false);
nm4.setVisible(false);
nm5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
String tr=(String)jComboBox1.getSelectedItem();
switch(tr){
    case "1":
        mem2.setVisible(false);
mem3.setVisible(false);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(false);
age3.setVisible(false);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(false);
nm3.setVisible(false);
nm4.setVisible(false);
nm5.setVisible(false);
        break;
    case "2":
        mem2.setVisible(true);
mem3.setVisible(false);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(true);
age3.setVisible(false);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(true);
nm3.setVisible(false);
nm4.setVisible(false);
nm5.setVisible(false);
        

        break;
        case "3":
            mem2.setVisible(true);
mem3.setVisible(true);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(true);
age3.setVisible(true);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(true);
nm3.setVisible(true);
nm4.setVisible(false);
nm5.setVisible(false);
         
    
        break;
            case "4":
                mem2.setVisible(true);
mem3.setVisible(true);
mem4.setVisible(true);
mem5.setVisible(false);
age2.setVisible(true);
age3.setVisible(true);
age4.setVisible(true);
age5.setVisible(false);
nm2.setVisible(true);
nm3.setVisible(true);
nm4.setVisible(true);
nm5.setVisible(false);
                
  
        break;
                case "5":
                 
                    mem2.setVisible(true);
        age2.setVisible(true);
   nm2.setVisible(true); 
        mem3.setVisible(true);
        age3.setVisible(true);
   nm3.setVisible(true);
        mem4.setVisible(true);
        age4.setVisible(true);
   nm4.setVisible(true); 
        mem5.setVisible(true);
        age5.setVisible(true);
   nm5.setVisible(true);    
 
        break;
        
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String a,b,c,j,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;
int rs=0; 
a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
j="DHFL";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4000);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4000);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(4000);
        break;
}

prem=Float.parseFloat(but1.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "1":
m1=mem1.getText();
        ag1=age1.getText();
        break;
        
    case "2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
        break;
        
    case "3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
        break;
        
    case "4":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
        break;
        
    case "5":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from life;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into life values('"+a+"',"+b+","+c+",'"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String a,b,c,j,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;
int rs=0; 
a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
j="HDFC";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);

switch (c){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4500);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4500);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(4500);
        break;
}

prem=Float.parseFloat(but2.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "1":
m1=mem1.getText();
        ag1=age1.getText();
        break;
        
    case "2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
        break;
        
    case "3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
        break;
        
    case "4":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
        break;
        
    case "5":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from life;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into life values('"+a+"',"+b+","+c+",'"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String a,b,c,j,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;
int rs=0; 
a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
j="Exide Life";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);
switch (c){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(3590);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(3590);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(3590);
        break;
}

prem=Float.parseFloat(but3.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "1":
m1=mem1.getText();
        ag1=age1.getText();
        break;
        
    case "2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
        break;
        
    case "3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
        break;
        
    case "4":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
        break;
        
    case "5":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from life;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into life values('"+a+"',"+b+","+c+",'"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String a,b,c,j,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;
int rs=0; 
a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
j="BAJAJ Allianz";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);
switch (c){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(5000);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(5000);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(5000);
        break;
}


prem=Float.parseFloat(but4.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "1":
m1=mem1.getText();
        ag1=age1.getText();
        break;
        
    case "2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
        break;
        
    case "3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
        break;
        
    case "4":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
        break;
        
    case "5":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from life;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into life values('"+a+"',"+b+","+c+",'"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String bn,c;
bn=JOptionPane.showInputDialog(this,"<html><font face=rockwell size=7>Enter Your Name",null,3);
        try{
     Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from life where name='"+bn+"';";
    ResultSet rs=st.executeQuery(qry);
    while(rs.next()){
        
        String ei=rs.getString("name");
        String in=rs.getString("amount");
        String p=rs.getString("no_of_mem");
        String m1=rs.getString("mem1");
        String a1=rs.getString("age1");
        
        String m2=rs.getString("mem2");
        String a2=rs.getString("age2");
        
        String m3=rs.getString("mem3");
        String a3=rs.getString("age3");
        
        String m4=rs.getString("mem4");
        String a4=rs.getString("age4");
        
        String m5=rs.getString("mem5");
        String a5=rs.getString("age5");
        
        String ins=rs.getString("INS_COMP");
        String co=rs.getString("Totalcover_Rs");
        String pr=rs.getString("premium");
        if(bn.equals(ei)){
            switch(p){
                case "1":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>No. of Members :- "+p+"<br>1st Member :- "+m1+"<br>1st Member Age :- "+a1+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
        break;
                      case "2":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>No. of Members :- "+p+"<br>1st Member :- "+m1+"<br>1st Member Age :- "+a1+"<br>2nd Member :- "+m2+"<br>2nd Member Age :- "+a2+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
 break;
                      case "3":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>No. of Members :- "+p+"<br>1st Member :- "+m1+"<br>1st Member Age :- "+a1+"<br>2nd Member :- "+m2+"<br>2nd Member Age :- "+a2+"<br>3rd Member :- "+m3+"<br> 3rd Member Age :- "+a3+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
break;
                      case "4":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>No. of Members :- "+p+"<br>1st Member :- "+m1+"<br>1st Member Age :- "+a1+"<br>2nd Member :- "+m2+"<br>2nd Member Age :- "+a2+"<br>3rd Member :- "+m3+"<br> 3rd Member Age :- "+a3+"<br> 4th Member :- "+m4+"<br>4th Member Age :- "+a4+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
break;
                      case "5":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>No. of Members :- "+p+"<br>1st Member :- "+m1+"<br>1st Member Age :- "+a1+"<br>2nd Member :- "+m2+"<br>2nd Member Age :- "+a2+"<br>3rd Member :- "+m3+"<br> 3rd Member Age :- "+a3+"<br> 4th Member :- "+m4+"<br>4th Member Age :- "+a4+"<br> 5th Member :- "+m5+"<br>5th Member Age :- "+a5+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
break;
            
            }
        }
    else if(!rs.next())
  
      JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name not Found <br> Please Add to Cart first",null,0);
}}
catch(Exception ss){

}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String bnn,a,b,c,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;;
 String cab[]=new String[4];
        cab[0]="DHFL";
        cab[1]="HDFC";
        cab[2]="BAJAJ Allianz";
        cab[3]="Exide Life";
  
bnn=JOptionPane.showInputDialog(this,"<html><font face=rockwell size=7>Enter Name where you want to Change",null,3);
Object cpp=JOptionPane.showInputDialog(null,null, "Select Company :- ",JOptionPane.QUESTION_MESSAGE,null,cab,"DHFL");

a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();

switch(c){
    case "1":
m1=mem1.getText();
        ag1=age1.getText();
        break;
        
    case "2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
        break;
        
    case "3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
        break;
        
    case "4":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
        break;
        
    case "5":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        break;
        
}

    Float cov = null,prem = null;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);

     
         
         if(cpp.equals(cab[0])){
      


switch (c){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4000);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4000);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(4000);
        break;
}

prem=Float.parseFloat(but1.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

        
            


    }
else        if(cpp.equals(cab[1])){
   switch (c){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4500);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(4500);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(4500);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(4500);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(4500);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(4500);
        break;
}

prem=Float.parseFloat(but2.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

        }
    else    if(cpp.equals(cab[2])){
switch (c){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(5000);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(5000);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(5000);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(5000);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(5000);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(5000);
        break;
}


prem=Float.parseFloat(but4.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

  
        }
    else    if(cpp.equals(cab[3])){
            
       switch (c){
    case "1":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "2":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
p4=0f;
p5=0f;
break;

    case "4":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(3590);
p5=0f;
break;

    case "5":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(3590);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(3590);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(3590);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(3590);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(3590);
        break;
}

prem=Float.parseFloat(but3.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);
        
       }     
        
        try{
     Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="Update life set name='"+a+"',amount="+b+",no_of_mem="+c+",mem1='"+m1+"',age1="+ag1+",mem2='"+m2+"',age2="+ag2+",mem3='"+m3+"',age3="+ag3+",mem4='"+m4+"',age4="+ag4+",mem5='"+m5+"',age5="+ag5+",INS_COMP='"+cpp+"',Totalcover_Rs="+cov+",premium="+prem+" where name='"+bnn+"';";
           st.executeUpdate(qry);
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Detail's Modified Successfully",null,2);
    
        }
        catch(Exception tt){
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIFEins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIFEins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAR_INS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAR_INS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LIFEins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JTextField age1;
    private javax.swing.JTextField age2;
    private javax.swing.JTextField age3;
    private javax.swing.JTextField age4;
    private javax.swing.JTextField age5;
    private javax.swing.JCheckBox b1;
    private javax.swing.JCheckBox b2;
    private javax.swing.JCheckBox b3;
    private javax.swing.JCheckBox b4;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JTextField ci;
    private javax.swing.JCheckBox d1;
    private javax.swing.JCheckBox d2;
    private javax.swing.JCheckBox d3;
    private javax.swing.JCheckBox d4;
    private javax.swing.JTextField ea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mem1;
    private javax.swing.JTextField mem2;
    private javax.swing.JTextField mem3;
    private javax.swing.JTextField mem4;
    private javax.swing.JTextField mem5;
    private javax.swing.JLabel nm1;
    private javax.swing.JLabel nm2;
    private javax.swing.JLabel nm3;
    private javax.swing.JLabel nm4;
    private javax.swing.JLabel nm5;
    // End of variables declaration//GEN-END:variables
}
