
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1232
 */
public class TRAVEL_INS extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public TRAVEL_INS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        age1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        con = new javax.swing.JTextField();
        d1 = new javax.swing.JCheckBox();
        d2 = new javax.swing.JCheckBox();
        b3 = new javax.swing.JCheckBox();
        ci = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nm2 = new javax.swing.JLabel();
        ea = new javax.swing.JTextField();
        a1 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JCheckBox();
        b2 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        d3 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        nm3 = new javax.swing.JLabel();
        nm4 = new javax.swing.JLabel();
        nm5 = new javax.swing.JLabel();
        nm1 = new javax.swing.JLabel();
        mem1 = new javax.swing.JTextField();
        mem2 = new javax.swing.JTextField();
        mem3 = new javax.swing.JTextField();
        mem4 = new javax.swing.JTextField();
        mem5 = new javax.swing.JTextField();
        age2 = new javax.swing.JTextField();
        age3 = new javax.swing.JTextField();
        age4 = new javax.swing.JTextField();
        age5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nm6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("<");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));
        getContentPane().add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, 40, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Top Rated Companies");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 330, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/bajaj.jpg"))); // NOI18N
        jLabel4.setText("   ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/DHFL.png"))); // NOI18N
        jLabel5.setText("   ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/max life.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 100, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/LIC.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Travelling to :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Where are you ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Enter Name :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 100, -1));

        con.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 120, -1));

        d1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d1.setText("Alltime Currency Cash Service cover (Rs.570)");
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        d2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d2.setText("Emergency Helpline Service (Rs.2990)  ");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 300, -1));

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setText("Renew Insurance AnyTime 30% less (free)");
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 300, -1));

        ci.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Travellers :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 90, -1));

        nm2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm2.setText("Spouse Name");
        getContentPane().add(nm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 90, -1));

        ea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(ea, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 110, -1));

        a1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a1.setText("Alltime Currency Cash Service cover (Rs.470)");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        a2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a2.setText("Emergency Helpline Service (Rs.2140)  ");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setText("Alltime Currency Cash Service cover (Rs.320)");
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setText("Emergency Helpline Service (Rs.2560)");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 300, -1));

        a3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a3.setText("Renew Insurance AnyTime 25% less (free) ");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, -1));

        c1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c1.setText("Alltime Currency Cash Service cover (Rs.410)");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        c2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c2.setText("Emergency Helpline Service (Rs.2000)");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 300, -1));

        d3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d3.setText("Renew Insurance AnyTime 30% less (free) ");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 300, -1));

        c3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c3.setText("Renew Insurance AnyTime 25% less (free) ");
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        but1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but1.setText("Count my Premium/yr.");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        getContentPane().add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        but2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but2.setText("Count my Premium/yr.");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });
        getContentPane().add(but2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        but3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but3.setText("Count my Premium/yr.");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });
        getContentPane().add(but3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        but4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but4.setText("Count my Premium/yr.");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });
        getContentPane().add(but4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setText("Enter Amount/pr.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 130, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Self", "+ Spouse", "+ Child-1", "+ Child-2", "+ Child-3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, -1, -1));

        nm3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm3.setText("Child-1 Name");
        getContentPane().add(nm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 90, -1));

        nm4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm4.setText("Child-2 Name");
        getContentPane().add(nm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 90, -1));

        nm5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm5.setText("Child-3 Name");
        getContentPane().add(nm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 90, -1));

        nm1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm1.setText("Your Name ");
        getContentPane().add(nm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 70, -1));
        getContentPane().add(mem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 100, -1));
        getContentPane().add(mem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 100, -1));
        getContentPane().add(mem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 100, -1));
        getContentPane().add(mem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 100, -1));
        getContentPane().add(mem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 100, -1));
        getContentPane().add(age2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 40, -1));
        getContentPane().add(age3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 40, -1));
        getContentPane().add(age4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 40, -1));
        getContentPane().add(age5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 540, 40, -1));

        jLabel10.setText("(Money will be Assured Back if Not Used)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        nm6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nm6.setText("Age");
        getContentPane().add(nm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 30, -1));

        jLabel14.setText("(Money will be Assured Back if Not Used)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jLabel16.setText("(Money will be Assured Back if Not Used)");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel17.setText("(Money will be Assured Back if Not Used)");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ADD TO CART");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("ADD TO CART");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("OPEN CART");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("MODIFY DETAILS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("ADD TO CART");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jk/backkkground.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new main_site().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed

        String a,b,c,d;

a=ci.getText();
b=ea.getText();
c=mem1.getText();
d=con.getText();
if(a.isEmpty() || b.isEmpty() || c.isEmpty() || d.isEmpty()){
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);}
Float cov=0f;
if(a1.isSelected())
cov+=470;
if(a2.isSelected())
cov+=2140;
if(a3.isSelected())
cov+=0;


        
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);


    

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(400);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(400);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(400);
        break;
}


pre=p1+p2+p3+p4+p5+cov;
but1.setText(""+pre);

// TODO add your handling code here:
    }//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
String a,b,c,d;

a=ci.getText();
b=ea.getText();
c=mem1.getText();
d=con.getText();
if(a.isEmpty() || b.isEmpty() || c.isEmpty() || d.isEmpty()){
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);}
Float cov=0f;
if(b1.isSelected())
cov+=320;
if(b2.isSelected())
cov+=2560;
if(b3.isSelected())
cov+=0;


        
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);


    

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(300);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(300);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(300);
        break;
}


pre=p1+p2+p3+p4+p5+cov;
but2.setText(""+pre);
        // TODO add your handling code here:
    }//GEN-LAST:event_but2ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
String a,b,c,d;

a=ci.getText();
b=ea.getText();
c=mem1.getText();
d=con.getText();
if(a.isEmpty() || b.isEmpty() || c.isEmpty() || d.isEmpty()){
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);}
Float cov=0f;
if(c1.isSelected())
cov+=410;
if(c2.isSelected())
cov+=2000;
if(c3.isSelected())
cov+=0;


        
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);


    

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(350);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(350);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(350);
        break;
}


pre=p1+p2+p3+p4+p5+cov;
but3.setText(""+pre);
    }//GEN-LAST:event_but3ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
String a,b,c,d;

a=ci.getText();
b=ea.getText();
c=mem1.getText();
d=con.getText();
if(a.isEmpty() || b.isEmpty() || c.isEmpty() || d.isEmpty()){
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=15>Please Enter Details",null,3);}
Float cov=0f;
if(d1.isSelected())
cov+=570;
if(d2.isSelected())
cov+=2990;
if(d3.isSelected())
cov+=0;


        
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);


    

String cb = (String)jComboBox1.getSelectedItem();
switch (cb){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(450);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(450);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(450);
        break;
}


pre=p1+p2+p3+p4+p5+cov;
but4.setText(""+pre);
    }//GEN-LAST:event_but4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
mem2.setVisible(false);
mem3.setVisible(false);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(false);
age3.setVisible(false);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(false);
nm3.setVisible(false);
nm4.setVisible(false);
nm5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
String tr=(String)jComboBox1.getSelectedItem();
switch(tr){
    case "Self":
        mem2.setVisible(false);
mem3.setVisible(false);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(false);
age3.setVisible(false);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(false);
nm3.setVisible(false);
nm4.setVisible(false);
nm5.setVisible(false);
        break;
    case "+ Spouse":
        mem2.setVisible(true);
mem3.setVisible(false);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(true);
age3.setVisible(false);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(true);
nm3.setVisible(false);
nm4.setVisible(false);
nm5.setVisible(false);
        

        break;
        case "+ Child-1":
            mem2.setVisible(true);
mem3.setVisible(true);
mem4.setVisible(false);
mem5.setVisible(false);
age2.setVisible(true);
age3.setVisible(true);
age4.setVisible(false);
age5.setVisible(false);
nm2.setVisible(true);
nm3.setVisible(true);
nm4.setVisible(false);
nm5.setVisible(false);
         
    
        break;
            case "+ Child-2":
                mem2.setVisible(true);
mem3.setVisible(true);
mem4.setVisible(true);
mem5.setVisible(false);
age2.setVisible(true);
age3.setVisible(true);
age4.setVisible(true);
age5.setVisible(false);
nm2.setVisible(true);
nm3.setVisible(true);
nm4.setVisible(true);
nm5.setVisible(false);
                
  
        break;
                case "+ Child-3":
                 
                    mem2.setVisible(true);
        age2.setVisible(true);
   nm2.setVisible(true); 
        mem3.setVisible(true);
        age3.setVisible(true);
   nm3.setVisible(true);
        mem4.setVisible(true);
        age4.setVisible(true);
   nm4.setVisible(true); 
        mem5.setVisible(true);
        age5.setVisible(true);
   nm5.setVisible(true);    
 
        break;
        
}        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String a,b,c,d,j,combo = null,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;

a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
d=con.getText();
j="BAJAJ Allianz";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);

switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(400);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(400);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(400);
        break;
}



prem=Float.parseFloat(but1.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "Self":
m1=mem1.getText();
        ag1=age1.getText();
        combo="1";
        break;
        
    case "+ Spouse":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        combo="2";
        break;
        
    case "+ Child-1":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        combo="3";
        break;
        
    case "+ Child-2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        combo="4";
        break;
        
    case "+ Child-3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        combo="5";
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from travel;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into travel values('"+a+"',"+b+",'"+d+"','"+combo+"','"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String a,b,c,d,j,combo = null,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;

a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
d=con.getText();
j="DHFL";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);

switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(300);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(300);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(300);
        break;
}




prem=Float.parseFloat(but2.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "Self":
m1=mem1.getText();
        ag1=age1.getText();
        combo="1";
        break;
        
    case "+ Spouse":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        combo="2";
        break;
        
    case "+ Child-1":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        combo="3";
        break;
        
    case "+ Child-2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        combo="4";
        break;
        
    case "+ Child-3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        combo="5";
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from travel;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into travel values('"+a+"',"+b+",'"+d+"','"+combo+"','"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String a,b,c,d,j,combo = null,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;

a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
d=con.getText();
j="LIC";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);

switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(350);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(350);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(350);
        break;
}




prem=Float.parseFloat(but3.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "Self":
m1=mem1.getText();
        ag1=age1.getText();
        combo="1";
        break;
        
    case "+ Spouse":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        combo="2";
        break;
        
    case "+ Child-1":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        combo="3";
        break;
        
    case "+ Child-2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        combo="4";
        break;
        
    case "+ Child-3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        combo="5";
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from travel;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into travel values('"+a+"',"+b+",'"+d+"','"+combo+"','"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String a,b,c,d,j,combo = null,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;

a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
d=con.getText();
j="MAX Life";
Float cov,prem;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);
switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(450);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(450);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(450);
        break;
}


prem=Float.parseFloat(but4.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

switch(c){
    case "Self":
m1=mem1.getText();
        ag1=age1.getText();
        combo="1";
        break;
        
    case "+ Spouse":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        combo="2";
        break;
        
    case "+ Child-1":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        combo="3";
        break;
        
    case "+ Child-2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        combo="4";
        break;
        
    case "+ Child-3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        combo="5";
        break;
        
}
        if(a.isEmpty() || b.equals("----------") || c.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter Details");
   
         try{
            Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from travel;";
    ResultSet rse=st.executeQuery(qry);
while(rse.next()){
        String ei=rse.getString("name");
        if(a.equals(ei))
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=6>Already Added on this Name<br>If you want to Mofify Details Please Click on MODIFY DETAILS",null,3);
}
            if(!rse.next()){
            String query="Insert into travel values('"+a+"',"+b+",'"+d+"','"+combo+"','"+m1+"',"+ag1+",'"+m2+"',"+ag2+",'"+m3+"',"+ag3+",'"+m4+"',"+ag4+",'"+m5+"',"+ag5+",'"+j+"',"+cov+","+prem+");";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "<html><font face=rockwell size=15>Added to Cart Successfully",null,2);
            }
                 
  }
       catch(Exception e){
       
       } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String bn,c;
bn=JOptionPane.showInputDialog(this,"<html><font face=rockwell size=7>Enter Your Name",null,3);
        try{
     Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="select * from travel where name='"+bn+"';";
    ResultSet rs=st.executeQuery(qry);
    while(rs.next()){
        
        String ei=rs.getString("name");
        String in=rs.getString("amount");
        String pq=rs.getString("travelling_To");
        String p=rs.getString("travellers");
        String m1=rs.getString("selfname");
        String a1=rs.getString("selfage");
        
        String m2=rs.getString("spousename");
        String a2=rs.getString("spouseage");
        
        String m3=rs.getString("child1name");
        String a3=rs.getString("child1age");
        
        String m4=rs.getString("child2name");
        String a4=rs.getString("child2age");
        
        String m5=rs.getString("child3name");
        String a5=rs.getString("child3age");
        
        String ins=rs.getString("INS_COMP");
        String co=rs.getString("Totalcover_Rs");
        String pr=rs.getString("premium");
        if(bn.equals(ei)){
            switch(p){
                case "1":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>Travelling To :- "+pq+"<br>No. of Travellers :- "+p+"<br> Traveller :- "+m1+"<br> Traveller's Age :- "+a1+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
        break;
                      case "2":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>Travelling To :- "+pq+"<br>No. of Travellers :- "+p+"<br>1st Traveller :- "+m1+"<br>1st Traveller's Age :- "+a1+"<br>2nd Traveller :- "+m2+"<br>2nd Traveller's Age :- "+a2+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
 break;
                      case "3":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>Travelling To :- "+pq+"<br>No. of Travellers :- "+p+"<br>1st Traveller :- "+m1+"<br>1st Traveller's Age :- "+a1+"<br>2nd Traveller :- "+m2+"<br>2nd Traveller's Age :- "+a2+"<br>3rd Traveller :- "+m3+"<br> 3rd Traveller's Age :- "+a3+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
break;
                      case "4":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>Travelling To :- "+pq+"<br>No. of Travellers :- "+p+"<br>1st Traveller :- "+m1+"<br>1st Traveller's Age :- "+a1+"<br>2nd Traveller :- "+m2+"<br>2nd Traveller's Age :- "+a2+"<br>3rd Traveller :- "+m3+"<br> 3rd Traveller's Age :- "+a3+"<br> 4th Traveller :- "+m4+"<br>4th Traveller's Age :- "+a4+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
break;
                      case "5":
          
       JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name :- "+ei+"<br>Amount :- "+in+"<br>Travelling To :- "+pq+"<br>No. of Travellers :- "+p+"<br>1st Traveller :- "+m1+"<br>1st Traveller's Age :- "+a1+"<br>2nd Traveller :- "+m2+"<br>2nd Traveller's Age :- "+a2+"<br>3rd Traveller :- "+m3+"<br> 3rd Traveller's Age :- "+a3+"<br> 4th Traveller :- "+m4+"<br>4th Traveller's Age :- "+a4+"<br> 5th Traveller :- "+m5+"<br>5th Travelleer's Age :- "+a5+"<br>Insurance Company :- "+ins+"<br>Cover Added Amount :- "+co+"<br>Premium per Annum :- "+pr,null,2);
break;
            
            }
        }
    else if(!rs.next())
  
      JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Name not Found <br> Please Add to Cart first",null,0);
}}
catch(Exception ss){

}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String bnn,a,b,c,d,combo=null,m1=null,m2=null,m3=null,m4=null,m5=null,ag1=null,ag2=null,ag3=null,ag4=null,ag5=null;
 String cab[]=new String[4];
        cab[0]="BAJAJ Allianz";
        cab[1]="DHFL";
        cab[2]="LIC";
        cab[3]="MAX Life";
  
bnn=JOptionPane.showInputDialog(this,"<html><font face=rockwell size=7>Enter Name where you want to Change",null,3);
Object cpp=JOptionPane.showInputDialog(null,null, "Select Company :- ",JOptionPane.QUESTION_MESSAGE,null,cab,"BAJAJ Allianz");

a=ci.getText();
b=ea.getText();
c=jComboBox1.getSelectedItem().toString();
d=con.getText();
    Float cov = null,prem = null;
Float m,pre,p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,a1 = null,a2 = null,a3 = null,a4 = null,a5 = null;
m=Float.parseFloat(b);

 
switch(c){
    case "Self":
m1=mem1.getText();
        ag1=age1.getText();
        combo="1";
        break;
        
    case "+ Spouse":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        combo="2";
        break;
        
    case "+ Child-1":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        combo="3";
        break;
        
    case "+ Child-2":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        combo="4";
        break;
        
    case "+ Child-3":
m1=mem1.getText();
        ag1=age1.getText();
        
m2=mem2.getText();
        ag2=age2.getText();
        
m3=mem3.getText();
        ag3=age3.getText();
        
m4=mem4.getText();
        ag4=age4.getText();
        
m5=mem5.getText();
        ag5=age5.getText();
        combo="5";
        break;
        
}    
         
         if(cpp.equals(cab[0])){
      
     switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(400);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(400);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(400);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(400);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(400);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(400);
        break;
}



prem=Float.parseFloat(but1.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);
      


    }
else        if(cpp.equals(cab[1])){

switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(300);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(300);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(300);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(300);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(300);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(300);
        break;
}




prem=Float.parseFloat(but2.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);


        }
    else    if(cpp.equals(cab[2])){
  switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(350);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(350);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(350);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(350);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(350);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(350);
        break;
}




prem=Float.parseFloat(but3.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

        }
    else    if(cpp.equals(cab[3])){
            switch (c){
    case "Self":
    a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
p2=0f;
p3=0f;
p4=0f;
p5=0f;
        break;

    case "+ Spouse":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
p3=0f;
p4=0f;
p5=0f;
        break;
        

    case "+ Child-1":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
p4=0f;
p5=0f;
break;

    case "+ Child-2":
        a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(450);
p5=0f;
break;

    case "+ Child-3":
         a1=Float.parseFloat(age1.getText());
p1=(m*a1)/(450);
a2=Float.parseFloat(age2.getText());
p2=(m*a2)/(450);
a3=Float.parseFloat(age3.getText());
p3=(m*a3)/(450);
a4=Float.parseFloat(age4.getText());
p4=(m*a4)/(450);
a5=Float.parseFloat(age5.getText());
p5=(m*a5)/(450);
        break;
}


prem=Float.parseFloat(but4.getText());
pre=p1+p2+p3+p4+p5;
cov=(float)(prem-pre);

       }     
        
        try{
     Class.forName("java.sql.Driver");
    Connection conn =DriverManager.getConnection("jdbc:mysql://localhost/jk","root","mysql");
    Statement st=conn.createStatement();
String qry="Update travel set name='"+a+"',amount="+b+",travelling_To='"+d+"',travellers="+combo+",selfname='"+m1+"',selfage="+ag1+",spousename='"+m2+"',spouseage="+ag2+",child1name='"+m3+"',child1age="+ag3+",child2name='"+m4+"',child2age="+ag4+",child3name='"+m5+"',child3age="+ag5+",INS_COMP='"+cpp+"',Totalcover_Rs="+cov+",premium="+prem+" where name='"+bnn+"';";
           st.executeUpdate(qry);
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=6>Detail's Modified Successfully",null,2);
    
        }
        catch(Exception tt){
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRAVEL_INS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRAVEL_INS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRAVEL_INS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRAVEL_INS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JTextField age1;
    private javax.swing.JTextField age2;
    private javax.swing.JTextField age3;
    private javax.swing.JTextField age4;
    private javax.swing.JTextField age5;
    private javax.swing.JCheckBox b1;
    private javax.swing.JCheckBox b2;
    private javax.swing.JCheckBox b3;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField con;
    private javax.swing.JCheckBox d1;
    private javax.swing.JCheckBox d2;
    private javax.swing.JCheckBox d3;
    private javax.swing.JTextField ea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mem1;
    private javax.swing.JTextField mem2;
    private javax.swing.JTextField mem3;
    private javax.swing.JTextField mem4;
    private javax.swing.JTextField mem5;
    private javax.swing.JLabel nm1;
    private javax.swing.JLabel nm2;
    private javax.swing.JLabel nm3;
    private javax.swing.JLabel nm4;
    private javax.swing.JLabel nm5;
    private javax.swing.JLabel nm6;
    // End of variables declaration//GEN-END:variables
}
